### ISSUE TITLE
 python fall_detection.py syntax error

### ISSUE THREAD

**Issue by kimud6003** [computationalcore/fall-detection#2]
I'm using a translator because my English is not good.

The following syntax error occurs when performing.

How can I solve this problem?

File "fall_detection.py", line 36
    def parse_args(parse_this=None) -> argparse.Namespace:
                                                           ^
SyntaxError: invalid syntax

**Comment by computationalcore** [comment]
Hi @kimud7, did you solved? Was it a problem with the project? Because I couldn't reproduce the error

**Comment by kimud6003** [comment]
O

2020년 5월 28일 (목) 오후 1:35, Vin Busquet <notifications@github.com>님이 작성:

> I'm sorry to bother you even though you're busy.
> It was just a question of Python version.
> It was my carelessness because I was a student and didn't know the video
> processing well.
> It's okay since I solved it.
>
