### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ofalah** [computationalcore/fall-detection#3]
mportError: cannot import name 'IEPlugin' from 'openvino.inference_engine'

in new openvino  no IEPlugin

how can fix this

thanks

**Comment by computationalcore** [comment]
You need to install the OpenVINO™ Toolkit, it have instructions [here](https://github.com/computationalcore/fall-detection#prerequisites). Also check if your hardware is compatible [here](https://github.com/computationalcore/fall-detection#hardware). 

For testing or video file inference independently of the hardware or too much dependencies I do recommend the Docker solution, you can find the instructions [here](https://github.com/computationalcore/fall-detection/blob/master/DOCKER.md).

I hope this useful.

Best Regards,

Vin Busquet
